spring:
  application:
    name: avengers
  config:
    use-legacy-processing: true
  profiles:
    active: dev
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        order_updates: true
        generate_statistics: false
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical:
          strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit:
          strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      thread-name-prefix: avengers-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: avengers-scheduling-
      pool:
        size: 2
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 9090
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /avengers